In [23]:
import numpy as np
import pandas as pd


data = pd.read_excel('baza.xlsx')
df = pd.DataFrame(data)
df.head(3)

,Date of the test,Name of the test,Test location,Session id,Registration with voucher (yes/no),External Candidate ID,Candidate first name,Candidate last name,Date of birth,Total score of the test*,Listening score,Reading score,Structure written expression score,Language Form and Meaning Score,Speaking score,Writing score,Score status
0,06/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",380125,No,NaN,NILUFARKHON,ESANALIEVA,16/10/1991,563,52,58,59,NaN,60,NaN,Valid
1,06/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",380125,No,NaN,NOZIMA,URUNOVA,23/04/1991,573,63,58,51,NaN,55,NaN,Valid
2,06/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",380125,No,NaN,ODINAXON,JALOLOVA,22/11/1996,387,45,31,40,NaN,-1,NaN,Valid

In [24]:
df[['Candidate first name','Candidate last name']].value_counts()

Candidate first name  Candidate last name
NILUFARKHON           ABDULLAEVA             4
MUKADDAMKHON          OKHUNOVA               4
ZEBINISO              ABDURAZAKOVA           4
MAKHBUBA              AZIMOVA                4
ISOKJON               KHAMDAMOV              4
                                            ..
JAMILAXON             IXTIYORXOJAYEVA        1
JALOLKHON             MUNAVVAROV             1
JALGAS                KURMANGALIEV           1
JAKHONGIR             MASHRABJONOV           1
ZUMRADKHON            MAKHKAMOVA             1
Name: count, Length: 418, dtype: int64

In [52]:
df1 = df[df['Candidate first name']=='NILUFARKHON']
df2 = df1[df1['Candidate last name']== 'ABDULLAEVA']
df2

,Date of the test,Name of the test,Test location,Session id,Registration with voucher (yes/no),External Candidate ID,Candidate first name,Candidate last name,Date of birth,Total score of the test*,Listening score,Reading score,Structure written expression score,Language Form and Meaning Score,Speaking score,Writing score,Score status
186,01/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",376941,No,NaN,NILUFARKHON,ABDULLAEVA,09/08/1990,593,62,61,55,NaN,-1,NaN,Valid
193,01/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",376939,No,NaN,NILUFARKHON,ABDULLAEVA,09/08/1990,593,62,61,55,NaN,58,NaN,Valid
207,01/10/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",376938,No,NaN,NILUFARKHON,ABDULLAEVA,09/08/1990,583,62,61,52,NaN,-1,NaN,Valid
251,30/09/2023,TOEFL ITP® Level 1 Test + Speaking - Instituti...,"Qo’qon chet tillar akademiyasi, Kokand, Uzbeki...",376932,No,NaN,NILUFARKHON,ABDULLAEVA,09/08/1990,563,59,57,53,NaN,41,NaN,Valid

In [60]:
for dt in df2.values:
    print(f'Imtihon kini {dt[0]}\n'
          f'Setion id {dt[3]}')

Imtihon kini 01/10/2023
Setion id 376941
Imtihon kini 01/10/2023
Setion id 376939
Imtihon kini 01/10/2023
Setion id 376938
Imtihon kini 30/09/2023
Setion id 376932